name = "quantum_computer_3_qubits"
version = "0.1.0"
defaultTargets = ["quantum_computer_3_qubits"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "308445d7985027f538e281e18df29ca16ede2ba3"

[[lean_lib]]
name = "QuantumComputer3Qubits"

[[lean_exe]]
name = "quantum_computer_3_qubits"
root = "Main"
