-- This module serves as the root of the `QuantumComputer3Qubits` library.
-- Import modules here that should be built as part of the library.
import QuantumComputer3Qubits.Formalization.QubitBasic
import QuantumComputer3Qubits.Formalization.QubitIndexed
import QuantumComputer3Qubits.Formalization.RegistryState
import QuantumComputer3Qubits.Formalization.Operators
import QuantumComputer3Qubits.Formalization.TransformOperators
import QuantumComputer3Qubits.Formalization.ComplexUtil
import QuantumComputer3Qubits.Formalization.InnerProduct
import QuantumComputer3Qubits.Formalization.LinearEquivRegistryState
import QuantumComputer3Qubits.Formalization.OuterProduct
import QuantumComputer3Qubits.Formalization.OrthonormalBasis

import QuantumComputer3Qubits.Tests.QubitBasic
import QuantumComputer3Qubits.Tests.QubitIndexed
import QuantumComputer3Qubits.Tests.RegistryState
import QuantumComputer3Qubits.Tests.LinearEquivRegistryState
import QuantumComputer3Qubits.Tests.StateExamples
import QuantumComputer3Qubits.Tests.TransformOperators
import QuantumComputer3Qubits.Tests.OuterProduct

#check Basis.equivFun
#check Basis.tensorProduct
